// Mocks generated by Mockito 5.4.6 from annotations
// in searvo/test/features/search/domain/usecases/get_autocomplete_suggestions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:searvo/features/search/domain/entities/search_mode.dart' as _i4;
import 'package:searvo/features/search/domain/entities/source_item.dart' as _i5;
import 'package:searvo/features/search/domain/repositories/search_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i2.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<dynamic> performSearch(
    String? query, {
    _i4.SearchMode? searchMode = _i4.SearchMode.search,
    required Map<String, dynamic>? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #performSearch,
              [query],
              {#searchMode: searchMode, #options: options},
            ),
            returnValue: _i3.Stream<dynamic>.empty(),
          )
          as _i3.Stream<dynamic>);

  @override
  _i3.Future<List<_i5.SourceItem>> searchDirect(
    String? query, {
    int? page = 1,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchDirect,
              [query],
              {#page: page, #category: category},
            ),
            returnValue: _i3.Future<List<_i5.SourceItem>>.value(
              <_i5.SourceItem>[],
            ),
          )
          as _i3.Future<List<_i5.SourceItem>>);

  @override
  _i3.Future<List<String>> getSuggestions(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestions, [query]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);
}
