// Mocks generated by Mockito 5.4.6 from annotations
// in searvo/test/features/search/rag/orchestration/agent_orchestrator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:searvo/features/llm/services/providers/base_llm_provider.dart'
    as _i4;
import 'package:searvo/features/llm/services/providers/llm_provider_manager.dart'
    as _i3;
import 'package:searvo/features/search/domain/entities/message_data.dart'
    as _i8;
import 'package:searvo/features/search/domain/entities/search_mode.dart' as _i9;
import 'package:searvo/features/search/rag/models/rag_models.dart' as _i10;
import 'package:searvo/features/search/rag/services/query_processing/prompt_engineer.dart'
    as _i7;
import 'package:searvo/features/search/domain/tools/search_tools.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeToolResult_0 extends _i1.SmartFake implements _i2.ToolResult {
  _FakeToolResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LLMProviderManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMProviderManager extends _i1.Mock
    implements _i3.LLMProviderManager {
  MockLLMProviderManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.BaseLLMProvider> get configuredProviders =>
      (super.noSuchMethod(
            Invocation.getter(#configuredProviders),
            returnValue: <_i4.BaseLLMProvider>[],
          )
          as List<_i4.BaseLLMProvider>);

  @override
  bool get hasConfiguredProvider =>
      (super.noSuchMethod(
            Invocation.getter(#hasConfiguredProvider),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.LLMProviderType> get availableProviders =>
      (super.noSuchMethod(
            Invocation.getter(#availableProviders),
            returnValue: <_i3.LLMProviderType>[],
          )
          as List<_i3.LLMProviderType>);

  @override
  Map<_i3.LLMProviderType, String> get providerNames =>
      (super.noSuchMethod(
            Invocation.getter(#providerNames),
            returnValue: <_i3.LLMProviderType, String>{},
          )
          as Map<_i3.LLMProviderType, String>);

  @override
  void registerProvider(
    _i3.LLMProviderType? type,
    _i4.BaseLLMProvider? provider,
  ) => super.noSuchMethod(
    Invocation.method(#registerProvider, [type, provider]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initializeProviders({
    String? openaiApiKey,
    String? googleApiKey,
    String? ollamaBaseUrl,
    String? openaiModel,
    String? googleModel,
    String? ollamaModel,
    String? openrouterApiKey,
    String? openrouterModel,
    String? anthropicApiKey,
    String? anthropicModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeProviders, [], {
              #openaiApiKey: openaiApiKey,
              #googleApiKey: googleApiKey,
              #ollamaBaseUrl: ollamaBaseUrl,
              #openaiModel: openaiModel,
              #googleModel: googleModel,
              #ollamaModel: ollamaModel,
              #openrouterApiKey: openrouterApiKey,
              #openrouterModel: openrouterModel,
              #anthropicApiKey: anthropicApiKey,
              #anthropicModel: anthropicModel,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setActiveProvider(_i3.LLMProviderType? type) => super.noSuchMethod(
    Invocation.method(#setActiveProvider, [type]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.BaseLLMProvider? getProvider(_i3.LLMProviderType? type) =>
      (super.noSuchMethod(Invocation.method(#getProvider, [type]))
          as _i4.BaseLLMProvider?);

  @override
  _i5.Future<String> generateResponse(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#generateResponse, [message]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateResponse, [message]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Stream<String> generateResponseStream(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#generateResponseStream, [message]),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  _i5.Future<String> generateResponseWithHistory(
    String? message,
    List<Map<String, dynamic>>? history,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateResponseWithHistory, [message, history]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateResponseWithHistory, [
                  message,
                  history,
                ]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<List<double>> generateEmbeddings(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#generateEmbeddings, [text]),
            returnValue: _i5.Future<List<double>>.value(<double>[]),
          )
          as _i5.Future<List<double>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PromptEngineer].
///
/// See the documentation for Mockito's code generation for more information.
class MockPromptEngineer extends _i1.Mock implements _i7.PromptEngineer {
  MockPromptEngineer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String formatConversationHistory(List<_i8.MessageData>? messages) =>
      (super.noSuchMethod(
            Invocation.method(#formatConversationHistory, [messages]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#formatConversationHistory, [messages]),
            ),
          )
          as String);

  @override
  String createSystemPrompt({
    _i9.SearchMode? searchMode = _i9.SearchMode.search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSystemPrompt, [], {
              #searchMode: searchMode,
            }),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#createSystemPrompt, [], {
                #searchMode: searchMode,
              }),
            ),
          )
          as String);

  @override
  String createUserPrompt(
    String? query,
    List<_i10.ContextChunk>? contextChunks, {
    String? attachmentContext,
    String? conversationContext,
    bool? hasUserProvidedUrls = false,
    bool? generateTitle = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createUserPrompt,
              [query, contextChunks],
              {
                #attachmentContext: attachmentContext,
                #conversationContext: conversationContext,
                #hasUserProvidedUrls: hasUserProvidedUrls,
                #generateTitle: generateTitle,
              },
            ),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #createUserPrompt,
                [query, contextChunks],
                {
                  #attachmentContext: attachmentContext,
                  #conversationContext: conversationContext,
                  #hasUserProvidedUrls: hasUserProvidedUrls,
                  #generateTitle: generateTitle,
                },
              ),
            ),
          )
          as String);

  @override
  String createUserPromptWithHistory(
    String? query,
    List<_i10.ContextChunk>? contextChunks, {
    String? conversationContext,
    String? attachmentContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createUserPromptWithHistory,
              [query, contextChunks],
              {
                #conversationContext: conversationContext,
                #attachmentContext: attachmentContext,
              },
            ),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #createUserPromptWithHistory,
                [query, contextChunks],
                {
                  #conversationContext: conversationContext,
                  #attachmentContext: attachmentContext,
                },
              ),
            ),
          )
          as String);

  @override
  String createAdaptivePrompt(
    String? query,
    List<_i10.ContextChunk>? contextChunks, {
    String? attachmentContext,
    String? conversationContext,
    bool? hasUserProvidedUrls = false,
    bool? generateTitle = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createAdaptivePrompt,
              [query, contextChunks],
              {
                #attachmentContext: attachmentContext,
                #conversationContext: conversationContext,
                #hasUserProvidedUrls: hasUserProvidedUrls,
                #generateTitle: generateTitle,
              },
            ),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #createAdaptivePrompt,
                [query, contextChunks],
                {
                  #attachmentContext: attachmentContext,
                  #conversationContext: conversationContext,
                  #hasUserProvidedUrls: hasUserProvidedUrls,
                  #generateTitle: generateTitle,
                },
              ),
            ),
          )
          as String);

  @override
  String createFallbackPrompt(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#createFallbackPrompt, [query]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#createFallbackPrompt, [query]),
            ),
          )
          as String);

  @override
  List<String> generateFollowUpQuestionsWithHistory(
    String? query,
    List<_i10.ContextChunk>? contextChunks,
    List<_i8.MessageData>? previousMessages, {
    bool? hasAttachments = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateFollowUpQuestionsWithHistory,
              [query, contextChunks, previousMessages],
              {#hasAttachments: hasAttachments},
            ),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> generateFollowUpQuestions(
    String? query,
    List<_i10.ContextChunk>? contextChunks, {
    bool? hasAttachments = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateFollowUpQuestions,
              [query, contextChunks],
              {#hasAttachments: hasAttachments},
            ),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, dynamic> validateQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#validateQuery, [query]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String enhanceQuery(String? originalQuery) =>
      (super.noSuchMethod(
            Invocation.method(#enhanceQuery, [originalQuery]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#enhanceQuery, [originalQuery]),
            ),
          )
          as String);

  @override
  Map<String, dynamic> analyzeContextQuality(
    List<_i10.ContextChunk>? contextChunks,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeContextQuality, [contextChunks]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String resolveContextualQuery(
    String? query,
    List<_i8.MessageData>? conversationHistory, {
    int? maxHistoryMessages = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resolveContextualQuery,
              [query, conversationHistory],
              {#maxHistoryMessages: maxHistoryMessages},
            ),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #resolveContextualQuery,
                [query, conversationHistory],
                {#maxHistoryMessages: maxHistoryMessages},
              ),
            ),
          )
          as String);

  @override
  String createAgentPrompt(String? query, String? toolDescriptions) =>
      (super.noSuchMethod(
            Invocation.method(#createAgentPrompt, [query, toolDescriptions]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#createAgentPrompt, [query, toolDescriptions]),
            ),
          )
          as String);
}

/// A class which mocks [SearchTool].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTool extends _i1.Mock implements _i2.SearchTool {
  MockSearchTool() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get icon =>
      (super.noSuchMethod(
            Invocation.getter(#icon),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#icon)),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.ToolResult> execute(
    String? query, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query], {#params: params}),
            returnValue: _i5.Future<_i2.ToolResult>.value(
              _FakeToolResult_0(
                this,
                Invocation.method(#execute, [query], {#params: params}),
              ),
            ),
          )
          as _i5.Future<_i2.ToolResult>);
}
