// Mocks generated by Mockito 5.4.6 from annotations
// in searvo/test/features/search/rag/bloc/rag_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:searvo/features/search/domain/entities/message_data.dart'
    as _i2;
import 'package:searvo/features/search/domain/entities/search_mode.dart' as _i6;
import 'package:searvo/features/search/rag/models/rag_models.dart' as _i5;
import 'package:searvo/features/search/rag/services/orchestration/rag_orchestrator.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageData_0 extends _i1.SmartFake implements _i2.MessageData {
  _FakeMessageData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RAGOrchestrator].
///
/// See the documentation for Mockito's code generation for more information.
class MockRAGOrchestrator extends _i1.Mock implements _i3.RAGOrchestrator {
  MockRAGOrchestrator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  _i4.Stream<_i5.RAGUpdate> generateRAGStream(
    String? query, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    bool? enableQueryEnhancement = true,
    bool? enableAdaptivePrompting = true,
    List<dynamic>? attachments,
    _i6.SearchMode? searchMode = _i6.SearchMode.search,
    List<_i2.MessageData>? previousMessages,
    int? maxHistoryMessages = 3,
    bool? isNewConversation = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateRAGStream,
              [query],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #enableQueryEnhancement: enableQueryEnhancement,
                #enableAdaptivePrompting: enableAdaptivePrompting,
                #attachments: attachments,
                #searchMode: searchMode,
                #previousMessages: previousMessages,
                #maxHistoryMessages: maxHistoryMessages,
                #isNewConversation: isNewConversation,
              },
            ),
            returnValue: _i4.Stream<_i5.RAGUpdate>.empty(),
          )
          as _i4.Stream<_i5.RAGUpdate>);

  @override
  _i4.Future<_i2.MessageData> generateRAGResponse(
    String? query, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    bool? enableQueryEnhancement = true,
    bool? enableAdaptivePrompting = true,
    List<dynamic>? attachments,
    _i6.SearchMode? searchMode = _i6.SearchMode.search,
    dynamic Function(_i2.MessageData)? onSearchComplete,
    bool? isNewConversation = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateRAGResponse,
              [query],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #enableQueryEnhancement: enableQueryEnhancement,
                #enableAdaptivePrompting: enableAdaptivePrompting,
                #attachments: attachments,
                #searchMode: searchMode,
                #onSearchComplete: onSearchComplete,
                #isNewConversation: isNewConversation,
              },
            ),
            returnValue: _i4.Future<_i2.MessageData>.value(
              _FakeMessageData_0(
                this,
                Invocation.method(
                  #generateRAGResponse,
                  [query],
                  {
                    #maxSearchResults: maxSearchResults,
                    #maxRelevantDocuments: maxRelevantDocuments,
                    #maxContextLength: maxContextLength,
                    #enableQueryEnhancement: enableQueryEnhancement,
                    #enableAdaptivePrompting: enableAdaptivePrompting,
                    #attachments: attachments,
                    #searchMode: searchMode,
                    #onSearchComplete: onSearchComplete,
                    #isNewConversation: isNewConversation,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.MessageData>);

  @override
  _i4.Future<_i2.MessageData> generateRAGResponseWithHistory(
    String? query,
    List<_i2.MessageData>? previousMessages, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    int? maxHistoryMessages = 3,
    List<dynamic>? attachments,
    dynamic Function(_i2.MessageData)? onSearchComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateRAGResponseWithHistory,
              [query, previousMessages],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #maxHistoryMessages: maxHistoryMessages,
                #attachments: attachments,
                #onSearchComplete: onSearchComplete,
              },
            ),
            returnValue: _i4.Future<_i2.MessageData>.value(
              _FakeMessageData_0(
                this,
                Invocation.method(
                  #generateRAGResponseWithHistory,
                  [query, previousMessages],
                  {
                    #maxSearchResults: maxSearchResults,
                    #maxRelevantDocuments: maxRelevantDocuments,
                    #maxContextLength: maxContextLength,
                    #maxHistoryMessages: maxHistoryMessages,
                    #attachments: attachments,
                    #onSearchComplete: onSearchComplete,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.MessageData>);

  @override
  Map<String, dynamic> validateQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#validateQuery, [query]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String enhanceQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#enhanceQuery, [query]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#enhanceQuery, [query]),
            ),
          )
          as String);

  @override
  Map<String, dynamic> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> getPerformanceStats() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearMetrics() => super.noSuchMethod(
    Invocation.method(#clearMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> analyzeQueryComplexity(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeQueryComplexity, [query]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.Future<Map<String, dynamic>> performHealthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#performHealthCheck, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
