// Mocks generated by Mockito 5.4.6 from annotations
// in searvo/test/features/search/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:searvo/features/history/models/conversation_model.dart' as _i9;
import 'package:searvo/features/history/services/conversation_sync_service.dart'
    as _i15;
import 'package:searvo/features/search/models/message_branch_model.dart' as _i8;
import 'package:searvo/features/search/models/message_data.dart' as _i2;
import 'package:searvo/features/search/models/search_mode.dart' as _i13;
import 'package:searvo/features/search/models/search_provider_config.dart'
    as _i6;
import 'package:searvo/features/search/rag/models/rag_models.dart' as _i4;
import 'package:searvo/features/search/rag/services/data_ingestion/pdf_extractor_service.dart'
    as _i5;
import 'package:searvo/features/search/rag/services/query_processing/query_analyzer.dart'
    as _i3;
import 'package:searvo/features/search/services/conversation_manager.dart'
    as _i7;
import 'package:searvo/features/search/services/search_service.dart' as _i10;
import 'package:searvo/features/search/services/searxng_service.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageData_0 extends _i1.SmartFake implements _i2.MessageData {
  _FakeMessageData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryAnalysis_1 extends _i1.SmartFake implements _i3.QueryAnalysis {
  _FakeQueryAnalysis_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocument_2 extends _i1.SmartFake implements _i4.Document {
  _FakeDocument_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePDFContent_3 extends _i1.SmartFake implements _i5.PDFContent {
  _FakePDFContent_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchResponse_4 extends _i1.SmartFake
    implements _i6.SearchResponse {
  _FakeSearchResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationState_5 extends _i1.SmartFake
    implements _i7.ConversationState {
  _FakeConversationState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageBranchManager_6 extends _i1.SmartFake
    implements _i8.MessageBranchManager {
  _FakeMessageBranchManager_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationModel_7 extends _i1.SmartFake
    implements _i9.ConversationModel {
  _FakeConversationModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i10.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get isConfigured =>
      (super.noSuchMethod(Invocation.getter(#isConfigured), returnValue: false)
          as bool);

  @override
  String get activeProviderName =>
      (super.noSuchMethod(
            Invocation.getter(#activeProviderName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#activeProviderName),
            ),
          )
          as String);

  @override
  String get activeSearchProviderName =>
      (super.noSuchMethod(
            Invocation.getter(#activeSearchProviderName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#activeSearchProviderName),
            ),
          )
          as String);

  @override
  List<String> get initializationErrors =>
      (super.noSuchMethod(
            Invocation.getter(#initializationErrors),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasInitializationErrors =>
      (super.noSuchMethod(
            Invocation.getter(#hasInitializationErrors),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<_i4.RAGUpdate> performDirectSearchStream(
    String? query, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    bool? enableQueryEnhancement = true,
    bool? enableAdaptivePrompting = true,
    List<dynamic>? attachments,
    _i13.SearchMode? searchMode = _i13.SearchMode.search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #performDirectSearchStream,
              [query],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #enableQueryEnhancement: enableQueryEnhancement,
                #enableAdaptivePrompting: enableAdaptivePrompting,
                #attachments: attachments,
                #searchMode: searchMode,
              },
            ),
            returnValue: _i12.Stream<_i4.RAGUpdate>.empty(),
          )
          as _i12.Stream<_i4.RAGUpdate>);

  @override
  _i12.Stream<_i4.RAGUpdate> generateSearchStream(
    String? query, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    bool? enableQueryEnhancement = true,
    bool? enableAdaptivePrompting = true,
    List<dynamic>? attachments,
    _i13.SearchMode? searchMode = _i13.SearchMode.search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateSearchStream,
              [query],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #enableQueryEnhancement: enableQueryEnhancement,
                #enableAdaptivePrompting: enableAdaptivePrompting,
                #attachments: attachments,
                #searchMode: searchMode,
              },
            ),
            returnValue: _i12.Stream<_i4.RAGUpdate>.empty(),
          )
          as _i12.Stream<_i4.RAGUpdate>);

  @override
  _i12.Future<_i2.MessageData> generateSearchResponse(
    String? query, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    bool? enableQueryEnhancement = true,
    bool? enableAdaptivePrompting = true,
    List<dynamic>? attachments,
    _i13.SearchMode? searchMode = _i13.SearchMode.search,
    dynamic Function(_i2.MessageData)? onSearchComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateSearchResponse,
              [query],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #enableQueryEnhancement: enableQueryEnhancement,
                #enableAdaptivePrompting: enableAdaptivePrompting,
                #attachments: attachments,
                #searchMode: searchMode,
                #onSearchComplete: onSearchComplete,
              },
            ),
            returnValue: _i12.Future<_i2.MessageData>.value(
              _FakeMessageData_0(
                this,
                Invocation.method(
                  #generateSearchResponse,
                  [query],
                  {
                    #maxSearchResults: maxSearchResults,
                    #maxRelevantDocuments: maxRelevantDocuments,
                    #maxContextLength: maxContextLength,
                    #enableQueryEnhancement: enableQueryEnhancement,
                    #enableAdaptivePrompting: enableAdaptivePrompting,
                    #attachments: attachments,
                    #searchMode: searchMode,
                    #onSearchComplete: onSearchComplete,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i2.MessageData>);

  @override
  _i12.Future<_i2.MessageData> performDirectSearchResponse(
    String? query, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    bool? enableQueryEnhancement = true,
    bool? enableAdaptivePrompting = true,
    List<dynamic>? attachments,
    _i13.SearchMode? searchMode = _i13.SearchMode.search,
    dynamic Function(_i2.MessageData)? onSearchComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #performDirectSearchResponse,
              [query],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #enableQueryEnhancement: enableQueryEnhancement,
                #enableAdaptivePrompting: enableAdaptivePrompting,
                #attachments: attachments,
                #searchMode: searchMode,
                #onSearchComplete: onSearchComplete,
              },
            ),
            returnValue: _i12.Future<_i2.MessageData>.value(
              _FakeMessageData_0(
                this,
                Invocation.method(
                  #performDirectSearchResponse,
                  [query],
                  {
                    #maxSearchResults: maxSearchResults,
                    #maxRelevantDocuments: maxRelevantDocuments,
                    #maxContextLength: maxContextLength,
                    #enableQueryEnhancement: enableQueryEnhancement,
                    #enableAdaptivePrompting: enableAdaptivePrompting,
                    #attachments: attachments,
                    #searchMode: searchMode,
                    #onSearchComplete: onSearchComplete,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i2.MessageData>);

  @override
  _i12.Stream<_i4.RAGUpdate> generateFollowUpStream(
    String? query,
    List<_i2.MessageData>? previousMessages, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    int? maxHistoryMessages = 3,
    List<dynamic>? attachments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateFollowUpStream,
              [query, previousMessages],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #maxHistoryMessages: maxHistoryMessages,
                #attachments: attachments,
              },
            ),
            returnValue: _i12.Stream<_i4.RAGUpdate>.empty(),
          )
          as _i12.Stream<_i4.RAGUpdate>);

  @override
  _i12.Future<_i2.MessageData> generateFollowUpResponse(
    String? query,
    List<_i2.MessageData>? previousMessages, {
    int? maxSearchResults = 20,
    int? maxRelevantDocuments = 10,
    int? maxContextLength,
    int? maxHistoryMessages = 3,
    List<dynamic>? attachments,
    dynamic Function(_i2.MessageData)? onSearchComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateFollowUpResponse,
              [query, previousMessages],
              {
                #maxSearchResults: maxSearchResults,
                #maxRelevantDocuments: maxRelevantDocuments,
                #maxContextLength: maxContextLength,
                #maxHistoryMessages: maxHistoryMessages,
                #attachments: attachments,
                #onSearchComplete: onSearchComplete,
              },
            ),
            returnValue: _i12.Future<_i2.MessageData>.value(
              _FakeMessageData_0(
                this,
                Invocation.method(
                  #generateFollowUpResponse,
                  [query, previousMessages],
                  {
                    #maxSearchResults: maxSearchResults,
                    #maxRelevantDocuments: maxRelevantDocuments,
                    #maxContextLength: maxContextLength,
                    #maxHistoryMessages: maxHistoryMessages,
                    #attachments: attachments,
                    #onSearchComplete: onSearchComplete,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i2.MessageData>);

  @override
  Map<String, dynamic> validateQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#validateQuery, [query]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String enhanceQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#enhanceQuery, [query]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#enhanceQuery, [query]),
            ),
          )
          as String);

  @override
  Map<String, dynamic> analyzeQueryComplexity(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeQueryComplexity, [query]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.QueryAnalysis analyzeQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeQuery, [query]),
            returnValue: _FakeQueryAnalysis_1(
              this,
              Invocation.method(#analyzeQuery, [query]),
            ),
          )
          as _i3.QueryAnalysis);

  @override
  _i12.Future<_i4.Document> scrapeUrl({
    required String? url,
    bool? includeImages = false,
    bool? includeLinks = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scrapeUrl, [], {
              #url: url,
              #includeImages: includeImages,
              #includeLinks: includeLinks,
            }),
            returnValue: _i12.Future<_i4.Document>.value(
              _FakeDocument_2(
                this,
                Invocation.method(#scrapeUrl, [], {
                  #url: url,
                  #includeImages: includeImages,
                  #includeLinks: includeLinks,
                }),
              ),
            ),
          )
          as _i12.Future<_i4.Document>);

  @override
  _i12.Future<List<_i4.Document>> scrapeMultipleUrls(
    List<String>? urls, {
    bool? includeImages = false,
    int? maxConcurrent = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #scrapeMultipleUrls,
              [urls],
              {#includeImages: includeImages, #maxConcurrent: maxConcurrent},
            ),
            returnValue: _i12.Future<List<_i4.Document>>.value(
              <_i4.Document>[],
            ),
          )
          as _i12.Future<List<_i4.Document>>);

  @override
  _i12.Future<_i5.PDFContent> extractPdfContent(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#extractPdfContent, [url]),
            returnValue: _i12.Future<_i5.PDFContent>.value(
              _FakePDFContent_3(
                this,
                Invocation.method(#extractPdfContent, [url]),
              ),
            ),
          )
          as _i12.Future<_i5.PDFContent>);

  @override
  _i12.Future<_i6.SearchResponse> searchByType({
    required String? query,
    _i14.SearchType? searchType = _i14.SearchType.general,
    _i14.SearchRecency? recency = _i14.SearchRecency.any,
    int? maxResults = 10,
    String? language = 'auto',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchByType, [], {
              #query: query,
              #searchType: searchType,
              #recency: recency,
              #maxResults: maxResults,
              #language: language,
            }),
            returnValue: _i12.Future<_i6.SearchResponse>.value(
              _FakeSearchResponse_4(
                this,
                Invocation.method(#searchByType, [], {
                  #query: query,
                  #searchType: searchType,
                  #recency: recency,
                  #maxResults: maxResults,
                  #language: language,
                }),
              ),
            ),
          )
          as _i12.Future<_i6.SearchResponse>);

  @override
  Map<String, dynamic> getStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> getDetailedStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getDetailedStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<Map<String, dynamic>> testProvider() =>
      (super.noSuchMethod(
            Invocation.method(#testProvider, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<Map<String, dynamic>> performHealthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#performHealthCheck, []),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  void resetStatistics() => super.noSuchMethod(
    Invocation.method(#resetStatistics, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getPerformanceStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<void> reinitialize() =>
      (super.noSuchMethod(
            Invocation.method(#reinitialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [ConversationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationManager extends _i1.Mock
    implements _i7.ConversationManager {
  MockConversationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i7.ConversationState> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i12.Stream<_i7.ConversationState>.empty(),
          )
          as _i12.Stream<_i7.ConversationState>);

  @override
  _i7.ConversationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeConversationState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.ConversationState);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadConversation(
    String? conversationId,
    String? title,
    List<_i8.MessageBranchManager>? branches,
  ) => super.noSuchMethod(
    Invocation.method(#loadConversation, [conversationId, title, branches]),
    returnValueForMissingStub: null,
  );

  @override
  void clearConversation() => super.noSuchMethod(
    Invocation.method(#clearConversation, []),
    returnValueForMissingStub: null,
  );

  @override
  void setProcessing(bool? isProcessing) => super.noSuchMethod(
    Invocation.method(#setProcessing, [isProcessing]),
    returnValueForMissingStub: null,
  );

  @override
  void updateState({
    List<_i8.MessageBranchManager>? branches,
    String? conversationId,
    String? conversationTitle,
    bool? isProcessing,
  }) => super.noSuchMethod(
    Invocation.method(#updateState, [], {
      #branches: branches,
      #conversationId: conversationId,
      #conversationTitle: conversationTitle,
      #isProcessing: isProcessing,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateCurrentMessage(_i2.MessageData? newMessage) => super.noSuchMethod(
    Invocation.method(#updateCurrentMessage, [newMessage]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? message) => super.noSuchMethod(
    Invocation.method(#setError, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.MessageBranchManager startNewConversation(
    String? query, {
    String? providedId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startNewConversation,
              [query],
              {#providedId: providedId},
            ),
            returnValue: _FakeMessageBranchManager_6(
              this,
              Invocation.method(
                #startNewConversation,
                [query],
                {#providedId: providedId},
              ),
            ),
          )
          as _i8.MessageBranchManager);

  @override
  _i8.MessageBranchManager? addNewMessage(String? query) =>
      (super.noSuchMethod(Invocation.method(#addNewMessage, [query]))
          as _i8.MessageBranchManager?);

  @override
  _i8.MessageBranchManager? rewriteMessage(int? index) =>
      (super.noSuchMethod(Invocation.method(#rewriteMessage, [index]))
          as _i8.MessageBranchManager?);

  @override
  _i8.MessageBranchManager? editQuery(int? index, String? newQuery) =>
      (super.noSuchMethod(Invocation.method(#editQuery, [index, newQuery]))
          as _i8.MessageBranchManager?);

  @override
  void switchBranch(int? messageIndex, int? branchIndex) => super.noSuchMethod(
    Invocation.method(#switchBranch, [messageIndex, branchIndex]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConversationSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationSyncService extends _i1.Mock
    implements _i15.ConversationSyncService {
  MockConversationSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isCloudSyncEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isCloudSyncEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setCloudSyncEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setCloudSyncEnabled, [enabled]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i9.ConversationModel> saveConversation({
    required String? conversationId,
    required String? title,
    required List<_i8.MessageBranchManager>? messageBranches,
    List<String>? tags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveConversation, [], {
              #conversationId: conversationId,
              #title: title,
              #messageBranches: messageBranches,
              #tags: tags,
            }),
            returnValue: _i12.Future<_i9.ConversationModel>.value(
              _FakeConversationModel_7(
                this,
                Invocation.method(#saveConversation, [], {
                  #conversationId: conversationId,
                  #title: title,
                  #messageBranches: messageBranches,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i12.Future<_i9.ConversationModel>);

  @override
  _i12.Future<_i9.ConversationModel> updateConversation({
    required String? conversationId,
    String? title,
    List<_i8.MessageBranchManager>? messageBranches,
    bool? isPinned,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [], {
              #conversationId: conversationId,
              #title: title,
              #messageBranches: messageBranches,
              #isPinned: isPinned,
              #tags: tags,
            }),
            returnValue: _i12.Future<_i9.ConversationModel>.value(
              _FakeConversationModel_7(
                this,
                Invocation.method(#updateConversation, [], {
                  #conversationId: conversationId,
                  #title: title,
                  #messageBranches: messageBranches,
                  #isPinned: isPinned,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i12.Future<_i9.ConversationModel>);

  @override
  _i12.Future<_i9.ConversationModel?> getConversationById(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [conversationId]),
            returnValue: _i12.Future<_i9.ConversationModel?>.value(),
          )
          as _i12.Future<_i9.ConversationModel?>);

  @override
  _i12.Future<List<_i9.ConversationModel>> getAllConversations({
    bool? pinnedFirst = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, [], {
              #pinnedFirst: pinnedFirst,
            }),
            returnValue: _i12.Future<List<_i9.ConversationModel>>.value(
              <_i9.ConversationModel>[],
            ),
          )
          as _i12.Future<List<_i9.ConversationModel>>);

  @override
  _i12.Future<bool> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> deleteAllConversations() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllConversations, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> togglePin(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#togglePin, [conversationId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i9.ConversationModel>> searchConversations(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchConversations, [query]),
            returnValue: _i12.Future<List<_i9.ConversationModel>>.value(
              <_i9.ConversationModel>[],
            ),
          )
          as _i12.Future<List<_i9.ConversationModel>>);

  @override
  _i12.Future<void> syncAllToCloud() =>
      (super.noSuchMethod(
            Invocation.method(#syncAllToCloud, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<int> getConversationCount() =>
      (super.noSuchMethod(
            Invocation.method(#getConversationCount, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i9.ConversationModel>> getPinnedConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getPinnedConversations, []),
            returnValue: _i12.Future<List<_i9.ConversationModel>>.value(
              <_i9.ConversationModel>[],
            ),
          )
          as _i12.Future<List<_i9.ConversationModel>>);

  @override
  _i12.Future<Map<String, List<_i9.ConversationModel>>>
  getGroupedConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getGroupedConversations, []),
            returnValue:
                _i12.Future<Map<String, List<_i9.ConversationModel>>>.value(
                  <String, List<_i9.ConversationModel>>{},
                ),
          )
          as _i12.Future<Map<String, List<_i9.ConversationModel>>>);

  @override
  List<_i8.MessageBranchManager> convertMessagesToBranches(
    List<_i9.ConversationMessageModel>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#convertMessagesToBranches, [messages]),
            returnValue: <_i8.MessageBranchManager>[],
          )
          as List<_i8.MessageBranchManager>);

  @override
  _i12.Future<int> deleteConversations(List<String>? conversationIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversations, [conversationIds]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}
