// Mocks generated by Mockito 5.4.6 from annotations
// in searvo/test/features/search/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:searvo/features/history/database/conversation_database.dart'
    as _i4;
import 'package:searvo/features/history/models/conversation_model.dart' as _i5;
import 'package:searvo/features/history/services/conversation_database_service.dart'
    as _i12;
import 'package:searvo/features/search/data/datasources/search_data_source.dart'
    as _i6;
import 'package:searvo/features/search/data/models/search_stream_update.dart'
    as _i9;
import 'package:searvo/features/search/domain/entities/message_branch_manager.dart'
    as _i3;
import 'package:searvo/features/search/domain/entities/message_data.dart'
    as _i10;
import 'package:searvo/features/search/presentation/bloc/conversation_manager.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConversationState_0 extends _i1.SmartFake
    implements _i2.ConversationState {
  _FakeConversationState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageBranchManager_1 extends _i1.SmartFake
    implements _i3.MessageBranchManager {
  _FakeMessageBranchManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationDatabase_2 extends _i1.SmartFake
    implements _i4.ConversationDatabase {
  _FakeConversationDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationModel_3 extends _i1.SmartFake
    implements _i5.ConversationModel {
  _FakeConversationModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationsCompanion_5 extends _i1.SmartFake
    implements _i4.ConversationsCompanion {
  _FakeConversationsCompanion_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchDataSource extends _i1.Mock implements _i6.SearchDataSource {
  MockSearchDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<_i9.SearchStreamUpdate> streamSearch(
    String? query, {
    List<dynamic>? attachments,
    String? conversationId,
    List<Map<String, dynamic>>? previousMessages,
    String? searchType = 'general',
    bool? isNewConversation = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #streamSearch,
              [query],
              {
                #attachments: attachments,
                #conversationId: conversationId,
                #previousMessages: previousMessages,
                #searchType: searchType,
                #isNewConversation: isNewConversation,
              },
            ),
            returnValue: _i8.Stream<_i9.SearchStreamUpdate>.empty(),
          )
          as _i8.Stream<_i9.SearchStreamUpdate>);

  @override
  _i8.Stream<_i9.SearchStreamUpdate> streamFollowUp({
    required String? query,
    required List<_i10.MessageData>? previousMessages,
    int? maxHistoryMessages = 5,
    List<dynamic>? attachments,
    String? conversationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamFollowUp, [], {
              #query: query,
              #previousMessages: previousMessages,
              #maxHistoryMessages: maxHistoryMessages,
              #attachments: attachments,
              #conversationId: conversationId,
            }),
            returnValue: _i8.Stream<_i9.SearchStreamUpdate>.empty(),
          )
          as _i8.Stream<_i9.SearchStreamUpdate>);

  @override
  _i8.Future<Map<String, dynamic>> uploadDocument(_i11.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDocument, [file]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<String>> getSuggestions(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestions, [query]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getDiscoverArticles({
    String? topic = 'all',
    int? limit = 15,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoverArticles, [], {
              #topic: topic,
              #limit: limit,
            }),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<bool> checkHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkHealth, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConversationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationManager extends _i1.Mock
    implements _i2.ConversationManager {
  MockConversationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i2.ConversationState> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i8.Stream<_i2.ConversationState>.empty(),
          )
          as _i8.Stream<_i2.ConversationState>);

  @override
  _i2.ConversationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeConversationState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.ConversationState);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadConversation(
    String? conversationId,
    String? title,
    List<_i3.MessageBranchManager>? branches,
  ) => super.noSuchMethod(
    Invocation.method(#loadConversation, [conversationId, title, branches]),
    returnValueForMissingStub: null,
  );

  @override
  void clearConversation() => super.noSuchMethod(
    Invocation.method(#clearConversation, []),
    returnValueForMissingStub: null,
  );

  @override
  void setProcessing(bool? isProcessing) => super.noSuchMethod(
    Invocation.method(#setProcessing, [isProcessing]),
    returnValueForMissingStub: null,
  );

  @override
  void updateState({
    List<_i3.MessageBranchManager>? branches,
    String? conversationId,
    String? conversationTitle,
    bool? isProcessing,
  }) => super.noSuchMethod(
    Invocation.method(#updateState, [], {
      #branches: branches,
      #conversationId: conversationId,
      #conversationTitle: conversationTitle,
      #isProcessing: isProcessing,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateCurrentMessage(_i10.MessageData? newMessage) => super.noSuchMethod(
    Invocation.method(#updateCurrentMessage, [newMessage]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? message) => super.noSuchMethod(
    Invocation.method(#setError, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTitle(String? newTitle) => super.noSuchMethod(
    Invocation.method(#updateTitle, [newTitle]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.MessageBranchManager startNewConversation(
    String? query, {
    String? providedId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startNewConversation,
              [query],
              {#providedId: providedId},
            ),
            returnValue: _FakeMessageBranchManager_1(
              this,
              Invocation.method(
                #startNewConversation,
                [query],
                {#providedId: providedId},
              ),
            ),
          )
          as _i3.MessageBranchManager);

  @override
  _i3.MessageBranchManager? addNewMessage(String? query) =>
      (super.noSuchMethod(Invocation.method(#addNewMessage, [query]))
          as _i3.MessageBranchManager?);

  @override
  _i3.MessageBranchManager? rewriteMessage(int? index) =>
      (super.noSuchMethod(Invocation.method(#rewriteMessage, [index]))
          as _i3.MessageBranchManager?);

  @override
  _i3.MessageBranchManager? editQuery(int? index, String? newQuery) =>
      (super.noSuchMethod(Invocation.method(#editQuery, [index, newQuery]))
          as _i3.MessageBranchManager?);

  @override
  void switchBranch(int? messageIndex, int? branchIndex) => super.noSuchMethod(
    Invocation.method(#switchBranch, [messageIndex, branchIndex]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConversationDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationDatabaseService extends _i1.Mock
    implements _i12.ConversationDatabaseService {
  MockConversationDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ConversationDatabase get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeConversationDatabase_2(
              this,
              Invocation.getter(#database),
            ),
          )
          as _i4.ConversationDatabase);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.ConversationModel> saveConversation({
    required String? conversationId,
    required String? title,
    required List<_i3.MessageBranchManager>? messageBranches,
    List<String>? tags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveConversation, [], {
              #conversationId: conversationId,
              #title: title,
              #messageBranches: messageBranches,
              #tags: tags,
            }),
            returnValue: _i8.Future<_i5.ConversationModel>.value(
              _FakeConversationModel_3(
                this,
                Invocation.method(#saveConversation, [], {
                  #conversationId: conversationId,
                  #title: title,
                  #messageBranches: messageBranches,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.ConversationModel>);

  @override
  _i8.Future<_i5.ConversationModel> updateConversation({
    required String? conversationId,
    String? title,
    List<_i3.MessageBranchManager>? messageBranches,
    bool? isPinned,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [], {
              #conversationId: conversationId,
              #title: title,
              #messageBranches: messageBranches,
              #isPinned: isPinned,
              #tags: tags,
            }),
            returnValue: _i8.Future<_i5.ConversationModel>.value(
              _FakeConversationModel_3(
                this,
                Invocation.method(#updateConversation, [], {
                  #conversationId: conversationId,
                  #title: title,
                  #messageBranches: messageBranches,
                  #isPinned: isPinned,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.ConversationModel>);

  @override
  _i8.Future<_i5.ConversationModel?> getConversationByConversationId(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationByConversationId, [
              conversationId,
            ]),
            returnValue: _i8.Future<_i5.ConversationModel?>.value(),
          )
          as _i8.Future<_i5.ConversationModel?>);

  @override
  _i8.Future<List<_i5.ConversationModel>> getAllConversations({
    bool? pinnedFirst = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, [], {
              #pinnedFirst: pinnedFirst,
            }),
            returnValue: _i8.Future<List<_i5.ConversationModel>>.value(
              <_i5.ConversationModel>[],
            ),
          )
          as _i8.Future<List<_i5.ConversationModel>>);

  @override
  _i8.Future<Map<String, List<_i5.ConversationModel>>>
  getGroupedConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getGroupedConversations, []),
            returnValue:
                _i8.Future<Map<String, List<_i5.ConversationModel>>>.value(
                  <String, List<_i5.ConversationModel>>{},
                ),
          )
          as _i8.Future<Map<String, List<_i5.ConversationModel>>>);

  @override
  _i8.Future<List<_i5.ConversationModel>> searchConversations(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchConversations, [query]),
            returnValue: _i8.Future<List<_i5.ConversationModel>>.value(
              <_i5.ConversationModel>[],
            ),
          )
          as _i8.Future<List<_i5.ConversationModel>>);

  @override
  _i8.Future<bool> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<int> deleteConversations(List<String>? conversationIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversations, [conversationIds]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> deleteAllConversations() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllConversations, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> togglePin(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#togglePin, [conversationId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getConversationCount() =>
      (super.noSuchMethod(
            Invocation.method(#getConversationCount, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i5.ConversationModel>> getPinnedConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getPinnedConversations, []),
            returnValue: _i8.Future<List<_i5.ConversationModel>>.value(
              <_i5.ConversationModel>[],
            ),
          )
          as _i8.Future<List<_i5.ConversationModel>>);

  @override
  List<_i3.MessageBranchManager> convertMessagesToBranches(
    List<_i5.ConversationMessageModel>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#convertMessagesToBranches, [messages]),
            returnValue: <_i3.MessageBranchManager>[],
          )
          as List<_i3.MessageBranchManager>);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ConversationModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationModel extends _i1.Mock implements _i5.ConversationModel {
  MockConversationModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get conversationId =>
      (super.noSuchMethod(
            Invocation.getter(#conversationId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#conversationId),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  DateTime get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _FakeDateTime_4(this, Invocation.getter(#createdAt)),
          )
          as DateTime);

  @override
  DateTime get updatedAt =>
      (super.noSuchMethod(
            Invocation.getter(#updatedAt),
            returnValue: _FakeDateTime_4(this, Invocation.getter(#updatedAt)),
          )
          as DateTime);

  @override
  bool get isPinned =>
      (super.noSuchMethod(Invocation.getter(#isPinned), returnValue: false)
          as bool);

  @override
  int get messageCount =>
      (super.noSuchMethod(Invocation.getter(#messageCount), returnValue: 0)
          as int);

  @override
  List<String> get tags =>
      (super.noSuchMethod(Invocation.getter(#tags), returnValue: <String>[])
          as List<String>);

  @override
  List<_i5.ConversationMessageModel> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i5.ConversationMessageModel>[],
          )
          as List<_i5.ConversationMessageModel>);

  @override
  String get preview =>
      (super.noSuchMethod(
            Invocation.getter(#preview),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#preview),
            ),
          )
          as String);

  @override
  String get timeCategory =>
      (super.noSuchMethod(
            Invocation.getter(#timeCategory),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#timeCategory),
            ),
          )
          as String);

  @override
  _i4.ConversationsCompanion toDriftCompanion() =>
      (super.noSuchMethod(
            Invocation.method(#toDriftCompanion, []),
            returnValue: _FakeConversationsCompanion_5(
              this,
              Invocation.method(#toDriftCompanion, []),
            ),
          )
          as _i4.ConversationsCompanion);
}
